edit_uri: "tree/main/docs"

repo_name: RTS
repo_url: https://github.com/Daniele-Tentoni/rts

site_author: Daniele Tentoni <daniele.tentoni.1996@gmail.com>
site_description: RTS Documentation site
site_name: RTS Docs
site_url: https://rts.readthedocs.io/

nav:
  - Home: "index.md"
  - "Player Guides":
      - "Players": "players/index.md"
      - "Entities":
          - "Ruler": "players/entities/ruler.md"
          - "Tower": "players/entities/tower.md"
  - "Developer Guides":
      - "Developers": "developers/index.md"
      - "Getting started": "developers/getting_started.md"
      - "Unit testing": "developers/unit_testing.md"
      - "Roadmap": "developers/roadmap.md"

theme: readthedocs
