site_name: RTS Docs
site_url: https://rts.readthedocs.io/

nav:
  - Home: "index.md"
  - "Player Guides":
      - "Players": "players/index.md"
      - "Ruler": "players/ruler.md"
      - "Tower": "players/tower.md"

theme: readthedocs
