FONT_NAME = 'Arial'
FONT_SIZE = 15

GAME_NAME = 'Real Time Strategy'

PLAYERS_NUMBER = 1

RULER_COLOR = (255, 0, 255)
RULER_HEIGHT = 15
RULER_WIDTH = 15
RULER_SIZE = (RULER_WIDTH, RULER_HEIGHT)

TEXT_COLOR = (127, 255, 127)

TOWER_COLOR = (100, 100, 100)
TOWER_WIDTH = 25
TOWER_HEIGHT = 25
TOWER_SIZE = (TOWER_WIDTH, TOWER_HEIGHT)

SCREEN_COLOR = (21, 21, 21)
SCREEN_HEIGHT = 600
SCREEN_WIDTH = 800
SCREEN__SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

SOLDIER_COLOR = (0, 255, 255)
SOLDIER_RADIUS_AROUND_TOWER = 10
SOLDIER_HEIGHT = 5
SOLDIER_WIDTH = 5
SOLDIER_SIZE = (SOLDIER_WIDTH, SOLDIER_HEIGHT)